//
//  MRBrewOutputParser.h
//  MRBrew
//
//  Copyright (c) 2013 Marc Ransome <marc.ransome@fidgetbox.co.uk>
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to
//  deal in the Software without restriction, including without limitation the
//  rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
//  sell copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in
//  all copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
//  FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
//  DEALINGS IN THE SOFTWARE.
//

#import <Foundation/Foundation.h>

@class MRBrewOperation;

@interface MRBrewOutputParser : NSObject

/**-----------------------------------------------------------------------------
 * @name Accessing the Shared Output Parser
 * -----------------------------------------------------------------------------
 */

/** Returns the shared `MRBrewOutputParser` instance, creating it if necessary.
 */
+ (instancetype)sharedOutputParser;

/**-----------------------------------------------------------------------------
 * @name Parsing Objects
 * -----------------------------------------------------------------------------
 */

/** Returns an array of objects parsed from the output generated when performing
 * an operation using `MRBrew`'s `performOperation:delegate:` method (see
 * `MRBrewDelegate` for additional details). Parsing is supported only for
 * output generated by `MRBrewOperation` objects whose `name` property
 * (equivalent to the _command_ in Homebrew terminology) matches one of
 * `MRBrewOperationListIdentifier`, `MRBrewOperationSearchIdentifier` or
 * `MRBrewOperationOptionsIdentifier`.
 *
 * @param operation The operation object that generated the output.
 * @param output The output string to parse.
 * @return An array of objects parsed from an operation's output or `nil` if
 * the operation type is either unsupported or parsing failed. For operations
 * whose `name` property matches `MRBrewOperationListIdentifier` or
 * `MRBrewOperationSearchIdentifier`, the returned array may contain one or
 * more `MRBrewFormula` objects. For operations whose `name` property matches
 * `MRBrewOperationOptionsIdentifier`, the returned array may contain one or
 * more `MRBrewInstallOption` objects.
 */
- (NSArray *)objectsForOperation:(MRBrewOperation *)operation output:(NSString *)output;

@end
